spring:
  application:
    name             : santander-dev-week-2024
  datasource:
    url              : jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username         : sa
    password         : ''
  h2:
    console:
      enabled: true

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ${password}
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: ${password}
#  port: 8443

generative-ai:
  provider: "GEMINI"

openapi:
  base-url: https://api.openai.com
  apiKey: ${OPENAI_API_KEY}

gemini:
  base-url: https://generativelanguage.googleapis.com
  apiKey: ${GEMINI_API_KEY}
